### ISSUE TITLE
StringPackIds.java have nothing changed...

### ISSUE THREAD

**Issue by Lilyandlucy** [WhatsApp/StringPacks#2]
When I run the script 
`python3 ./stringpacks/scripts/assemble_string_packs.py --config ./{path_to}/config.json
`
The log shows 
`Updated: ./app/src/main/java/com/mg/compress/StringPackIds.java
INFO:root:Moving: ./app/src/main/res/values-zh/strings.xml
INFO:root:To file: ./app/string-packs/strings/._app_src_main_res_/values-zh/strings.xml`

And nothing happend except there is a comment added in the string.xml which is ""

Please help me~What's wrong with it?

**Comment by Ider** [comment]
Do you mind to share your content of values-zh/strings.xml with us so we can check whether it's because any special format in your xml?

**Comment by Lilyandlucy** [comment]
@Ider  In the directory  values-zh/strings.xml  , I just put one line in it 
Here is the content:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">字符串压缩</string>
</resources>
```
When I run the script, the xml seems like this:
`<?xml version="1.0" encoding="utf-8"?>

<resources>
    <string name="app_name">字符串压缩</string>
</resources>
`

**Comment by Lilyandlucy** [comment]
@Ider 
When the scripts run the method 
`get_resource_content_without_header`
In fact, the dstfile "./app/string-packs/strings/._app_src_main_res_/values-zh/strings.xml" doesn't exists...

**Comment by Lilyandlucy** [comment]
@Ider  I made a mistake in config.json... 
I can't get the meaning of  the params "packable_strings_directory"
