### ISSUE TITLE
WhatsApp camera is giving issues

### ISSUE THREAD

**Issue by Jassi10000** [WhatsApp/StringPacks#4]
The camera in the WhatsApp app on Android phone is experiencing issues , for a closer pic , the camera need to be moved very high from the target , but when the photo gets clicked it shows a very maximised  picture , please have a look at this glitch

**Comment by ashish29dec** [comment]
Hello @Jassi10000 ,

Thanks for reaching out. However, we can't address WhatsApp specific issues here. For any WhatsApp specific issues please raise your concerns via `Contact Us` option in the app itself.

**Comment by Jassi10000** [comment]
I agree sir , but many people are facing the same option that's why I thought of opening an issue here 
Anyways , thanks for telling , will try  <code>Contact Us </code> too
