### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by AleXDarkstalker99** [WhatsApp/StringPacks#6]
I would like to change the functions in WhatsaApp. this is when you exit from phone 1 and enter from phone 2. From phone 1, the function will close everything.I would like to switch to both phone 1 and phone 2 at the same time. how facebook works.

**Comment by ashish29dec** [comment]
Hello @AleXDarkstalker99 

Thanks for reaching out. However, we can't address WhatsApp specific issues here. For any WhatsApp specific issues please raise your concerns via `Contact Us` option in the app itself.
